import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
            <nav>
                <span id="title">
                    <span>Donnell</span>
                    <span>Fulwiler</span>
                </span>
                <ul className="list-none ">
                    <li></li>
                </ul>
            </nav>
                {children}
            </body>
        </html>
    );
}
